[build]
builder = "nixpacks"

[deploy]
startCommand = "streamlit run app/ui/app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
